### ISSUE TITLE
error: bbdb-record-name-lf: Wrong type argument: arrayp, nil 

### ISSUE THREAD

**Issue by zeltak** [emacs-helm/helm-bbdb#5] opened 2016-11-17 12:29 UTC
Hi 

this looks really neat. i get the following error:

```
bbdb-record-name-lf: Wrong type argument: arrayp, nil 
```

any clue?

Z

**Comment by thierryvolpiatto** [comment] 2016-11-17 14:43
zeltak notifications@github.com writes:

> Hi
> 
> this looks really neat. i get the following error:
> 
> bbdb-record-name-lf: Wrong type argument: arrayp, nil 
> 
> any clue?

backtrace please.

## 

Thierry

**Comment by zeltak** [comment] 2016-11-18 10:11
Hi. im not very technical but if i understand correct you wanted me to enter debug (via M-x) and then try to repeat the command and then paste the "backtrace" buffer? is so this is the paste

```
Debugger entered--entering a function:
* helm-bbdb()
  funcall-interactively(helm-bbdb)
  call-interactively(helm-bbdb record nil)
  command-execute(helm-bbdb record)
  #[257 "\304\305!\203\f\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"]("helm-bbdb")
  ivy-call()
  ivy-read("M-x " ("debug-on-entry" "debug" "mu4e" "counsel-bbdb-complete-mail" "wgrep-change-to-wgrep-mode" "ag-project-regexp" "yankpad-insert" "load-theme" "wl" "ranger" "eval-region" "customize-variable" "gnus" "popup-imenu" "counsel-find-file" "iedit-mode" "yankpad-edit" "ibuffer" "ansi-term" "peep-dired" "helm-colors" "pabbrev-mode" "isearch-forward" "org-babel-tangle" "dired-ranger-copy" "dired-up-directory" "link-hint-open-link" "helm-org-rifle-directories" "deer" "customize-group" "helm-find-files" "avy-goto-char-timer" "projectile-find-file" "endless/fill-or-unfill" "hydra-cheatsheet-dired/body" "elfeed" "dired-jump" "load-library" "deft" "shell" "multi-term" "helm-buffers-list" "bjm/move-file-here" "counsel-load-theme" "image-dired" "nlinum-mode" "dired-narrow" "org-cliplink" "dired-do-copy" "poly-org-mode" ...) :predicate nil :require-match t :history extended-command-history :action #[257 "\304\305!\203\f\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input "^" :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

```

if this is not what you had in mind id be happy to try to help debug this with a little guidance

thx alot

Z

**Comment by thierryvolpiatto** [comment] 2016-11-18 11:22
zeltak notifications@github.com writes:

> Hi. im not very technical but if i understand correct you wanted me to
> enter debug (via M-x) and then try to repeat the command and then
> paste the "backtrace" buffer? is so this is the paste

No.

1) M-x helm-find-files => navigate to helm-bbdb.el and hit M-L (load-file).
2) M-x toggle-debug-on-error
3) Start helm-bbdb to reproduce your bug.
4) Copy the relevant backtrace and send it here.

BTW Could you provide as well the exact steps to reproduce your bug.

Thanks.

NOTE: Step 1) is facultative but avoid having bytecode in the backtrace.

## 

Thierry

**Comment by zeltak** [comment] 2016-11-18 15:10
Hi again and thx for the help

so this is the backtrace result of the above steps:

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  bbdb-record-set-name(["zeltak" "" nil ("zeltak") nil nil nil ("ikloog@yahoo.com") nil nil] t t)
  bbdb-record-name-lf(["zeltak" "" nil ("zeltak") nil nil nil ("ikloog@yahoo.com") nil nil])
  bbdb("Zoe Mullan" nil)
  helm-bbdb-get-record("Zoe Mullan")
  mapcar(helm-bbdb-get-record ("Zoe Mullan"))
  helm-bbdb-view-person-action("Zoe Mullan")
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  helm-internal(helm-source-bbdb nil nil nil nil "*helm bbdb*" nil nil nil)
  apply(helm-internal (helm-source-bbdb nil nil nil nil "*helm bbdb*" nil nil nil))
  helm(helm-source-bbdb nil nil nil nil "*helm bbdb*" nil nil nil)
  apply(helm (helm-source-bbdb nil nil nil nil "*helm bbdb*" nil nil nil))
  helm(:sources helm-source-bbdb :buffer "*helm bbdb*")
  helm-other-buffer(helm-source-bbdb "*helm bbdb*")
  helm-bbdb()
  funcall-interactively(helm-bbdb)
  call-interactively(helm-bbdb record nil)
  command-execute(helm-bbdb record)
  #[257 "\304\305!\203\f\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"]("helm-bbdb")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "helm-find-files" "debug-on-entry" "debug" "mu4e" "counsel-bbdb-complete-mail" "yankpad-insert" "load-theme" "wl" "ranger" "eval-region" "customize-variable" "gnus" "popup-imenu" "counsel-find-file" "iedit-mode" "yankpad-edit" "ibuffer" "ansi-term" "peep-dired" "helm-colors" "pabbrev-mode" "isearch-forward" "org-babel-tangle" "dired-ranger-copy" "dired-up-directory" "link-hint-open-link" "helm-org-rifle-directories" "deer" "customize-group" "avy-goto-char-timer" "projectile-find-file" "endless/fill-or-unfill" "hydra-cheatsheet-dired/body" "elfeed" "dired-jump" "load-library" "deft" "shell" "multi-term" "helm-buffers-list" "bjm/move-file-here" "counsel-load-theme" "image-dired" "nlinum-mode" "dired-narrow" "org-cliplink" "dired-do-copy" "poly-org-mode" "fill-paragraph" ...) :predicate nil :require-match t :history extended-command-history :action #[257 "\304\305!\203\f\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input "^" :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

to reproduce i simply launch `helm-bbdb` then enter a search string and press enter

best

Z

**Comment by thierryvolpiatto** [comment] 2016-11-18 16:33
zeltak notifications@github.com writes:

> so this is the backtrace result of the above steps:

Great thanks, BTW can you reproduce with the last changes I made ?

## 

Thierry

**Comment by thierryvolpiatto** [comment] 2016-11-18 16:57
I can't reproduce, on which contact did you press ENTER "zeltak" or "zoe
mulan" ?

Which bbdb are you using, i.e do you have a old version or you have
installed recently from melpa ?

Can you reproduce from ./emacs-helm.sh (load only helm-bbdb.el once
started) ?

## 

Thierry

**Comment by zeltak** [comment] 2016-11-19 05:49
Hi 

I pressed zoe mulan in the example above

im using latest bbdb from melpa and this is the current config:

```
(use-package bbdb
 :ensure t
 :config
(setq bbdb-file "~/.emacs.d/bbdb")           ;; keep ~/ clean; set before loading
(require 'bbdb) 
(bbdb-initialize)

 )
```

> Can you reproduce from ./emacs-helm.sh (load only helm-bbdb.el once
> started) ?

im not sure im following what to do in the above?

thx again

Z

**Comment by thierryvolpiatto** [comment] 2016-11-19 19:58
zeltak notifications@github.com writes:

> Hi 
> 
> I pressed zoe mulan in the example above
> 
> im using latest bbdb from melpa and this is the current config:
> 
> ```
> (use-package bbdb
>  :ensure t
>  :config
> (setq bbdb-file "~/.emacs.d/bbdb")           ;; keep ~/ clean; set before loading
> (require 'bbdb) 
> (bbdb-initialize)
> 
>  )
> ```

You don't need to require bbdb and bbdb-file default is already
~/.emacs.d/bbdb

> > Can you reproduce from ./emacs-helm.sh (load only helm-bbdb.el once
> > started) ?
> 
> im not sure im following what to do in the above?

Start emacs from the shell script ./emacs-helm.sh.

## 

Thierry

**Comment by thierryvolpiatto** [comment] 2016-11-20 07:35
I still can't reproduce this bug, could you save your bbdb file and
start a new bbdb session with no contacts, create some new contacts and
try to reproduce.

1) Rename your bbdb file to bbdb_save
2) Restart emacs with this helm-bbdb config:
    (use-package bbdb
     :ensure t
     :config (bbdb-initialize))
3) M-x helm-bbdb
once started write e.g zoe and hit RET
then start recording contact
repeat this to have two or three contacts
4) restart helm-bbdb and RET on any contact
Can you reproduce bug now ?

## 

Thierry

**Comment by zeltak** [comment] 2016-11-21 13:37
Hi

indeed the above steps made helm-bbdb work :)

what are the next steps now? is my bbdb file the issue? is it unicode issues?

EDIT: i can confirm that when i recreate the bbdb file under ~/emacs.d/ the error returns
thx!

Z

**Comment by thierryvolpiatto** [comment] 2016-11-21 14:08
zeltak notifications@github.com writes:

> Hi
> 
> indeed the above steps made helm-bbdb work :)

Great.

> what are the next steps now? is my bbdb file the issue?

Yes, I think your bbdb file is corrupted or at least some entries are.
Perhaps try to record again all entries that fails in your bbdb file.

Where your bbdb file comes from ? Did you made it from a previous
version of bbdb ?

I can't find a bbdb documentation on how to upgrade a bbdb file to a
newer version, perhaps it is not a problem ?

> is it unicode issues?

I don't think so.

## 

Thierry

**Comment by zeltak** [comment] 2016-11-21 16:07
Ok success. i originally used this :
https://gitlab.com/iankelling/bbdb-csv-import/
to import a vcf file to bbdb and that gave the errors (on every contact)

i now moved to this:

https://github.com/redguardtoo/gmail2bbdb

and it seems there are no issues now :)

but on a related note, why dosent helm-bbdb show all associated info (like phone # etc), is there a way to configure it to show all info?

thx again!

z

**Comment by thierryvolpiatto** [comment] 2016-11-21 16:28
zeltak notifications@github.com writes:

> Ok success. i originally used this :
> https://gitlab.com/iankelling/bbdb-csv-import/
> to import a vcf file to bbdb and that gave the errors (on every contact)
> 
> i now moved to this:
> 
> https://github.com/redguardtoo/gmail2bbdb
> 
> and it seems there are no issues now :)

Great!

> but on a related note, why dosent helm-bbdb show all associated info
> (like phone # etc),

Not yet implemented :-), I will add a persistent action soon to show the
bbdb buffer for contact in other window, actually it popup in a split of
current helm window which is wrong.

## 

Thierry

**Comment by thierryvolpiatto** [comment] 2016-11-21 17:51
Now persistent action is implemented.
Seems your original issue is now fixed, so I am closing now.
Thanks.

**Closed as completed by thierryvolpiatto** 2016-11-21 17:51 UTC
